- name: Deploy Python Application
  hosts: dev
  roles:
    - name: current_time_app
      vars:
        app_name: app_python
        docker_image_name: iskanred/app_python
        docker_image_version: 1.0.0
        docker_container_name: app_python_container
        internal_port: 8080
        external_port: 8081
        web_app_full_stop: true
        web_app_full_wipe: true
