- name: Wipe Application using Docker Compose
  when:
    - web_app_full_stop
    - web_app_full_wipe
  block:
    - name: Remove application's directory with it's content
      file:
        path: "{{ app_dir }}"
        state: absent