apiVersion: apps/v1
kind: Deployment
metadata:
  name: current-time-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: current-time-server
  template:
    metadata:
      labels:
        app: current-time-server
    spec:
      containers:
        - name: current-time-server
          image: iskanred/current-time-server:1.0.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 512Mi
              cpu: 1
            limits:
              memory: 512Mi
              cpu: 1
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 1
            failureThreshold: 10000
          env:
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: current-time-server-secret
                  key: secret
          volumeMounts:
            - name: current-time-server-config-json-volume
              mountPath: /etc/config
      volumes:
        - name: current-time-server-config-json-volume
          configMap:
            name: current-time-server-config-json
