apiVersion: v1

kind: Config
current-context: minikube

clusters:
  - name: minikube
    cluster:
      server: https://127.0.0.1:32774
      certificate-authority: /Users/i.nafikov/.minikube/ca.crt
      extensions:
        - name: cluster_info
          extension:
            provider: minikube.sigs.k8s.io
            version: v1.35.0
            last-update: Tue, 18 Feb 2025 16:47:47 MSK

contexts:
  - name: minikube
    context:
      cluster: minikube
      user: minikube
      namespace: default
      extensions:
        - name: context_info
          extension:
            provider: minikube.sigs.k8s.io
            version: v1.35.0
            last-update: Tue, 18 Feb 2025 16:47:47 MSK

users:
  - name: minikube
    user:
      client-certificate: /Users/i.nafikov/.minikube/profiles/minikube/client.crt
      client-key: /Users/i.nafikov/.minikube/profiles/minikube/client.key
