apiVersion: v1
kind: Service
metadata:
  name: current-time-server-service
spec:
  type: LoadBalancer
  selector:
    app: current-time-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  externalIPs:
    - 192.168.49.2
