spring:
  application:
    name: current-time-server

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics
  prometheus:
    metrics:
      export:
        enabled: true
